// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqfpweplcczckrwedzad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZnB3ZXBsY2N6Y2tyd2VkemFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjU2NDYsImV4cCI6MjA3MjA0MTY0Nn0.SU0ZDdOiJEbXaqij8xZNTe4yJRM-OqvhH8Ubf3PWEOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});